name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      scriptjs-file: ${{ steps.publishJS.outputs.scriptjs-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Publish Js filename
        id: publishJS
        run: find dist/assets/*.js -type f -execdir echo 'scriptjs-file={}' >> $GITHUB_OUTPUT ';'
      - name: upload artifacts
        uses: actions/upload-artifact@v7.0.0
        with:
          name: dist files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8.0.1
        with:
            name: dist files
      - name: Output Contents
        run: ls
      - name: Output files
        run: echo "${{needs.build.outputs.scriptjs-file}}"
      - name: Deploy
        run: echo "Deploying..."
